INSERT INTO entries (lastName,firstName,countryCode,gender,mutationEntries,physician)
  VALUES ('Ardelean', 'Mihai','RO','M','A2M_12p13.31_Alzheimers Disease,AACS_12q24.31_Traheal Cancer','Philip Morris');
INSERT INTO entries (lastName,firstName,countryCode,gender,mutationEntries,physician)
  VALUES ('Andras', 'Maria','RO','F','A2M_12p13.31_Alzheimers Disease,AACS_12q24.31_Traheal Cancer','Oltean Marin');